name: CI 

on:

  pull_request:
    branches: [ "main" ]

jobs:
  run-test:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup JDK 11 with cache Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven     
     
    - name: Prepare Jenkins data
      run: |
          cat ${{ github.workspace }}/jenkins_data/jenkins_backup0* > ${{ github.workspace }}/jenkins_backup.tar
          md5sum ${{ github.workspace }}/jenkins_backup.tar
          
     - name: Extract Jenkins data and set permission
      run: |
          tar -xzvf ./jenkins_backup.tar
          chmod -R 777 ./jenkins_backup/var/jenkins_home

    - name: Docker login
      run: echo ${{ secrets.DOCKER_PAS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
    
    - name: Run Jenkins in Docker
      run: docker run --rm --detach -p 8080:8080 -p 50000:50000 -v ${{ github.workspace }}/jenkins_backup/var/jenkins_home:/var/jenkins_home jenkins/jenkins:2.332.3-lts-jdk11

    - name: Change wrapper permissions
      run: chmod +x ./.github/wait-for-jenkins.sh 
      
    - name: Wait for the Jenkins
      run: ./.github/wait-for-jenkins.sh        
      
    - name: Maven runs tests
      run: mvn clean test 
      env:
          CHROME_OPTIONS: --disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless;--window-size=1920,1080
          APP_OPTIONS: port=8080;admin.username=${{ secrets.ADMIN_USER }};admin.password=${{ secrets.ADMIN_PAS }}
          CI_RUN: true
      continue-on-error: true
      
    - name: Check on failures
      if: steps.test.outcome != 'success'
      run: exit 1
